<% require 'radian/chef' %>
<% config = Radian::Chef %>
<% aws_access_key = ENV['AWS_ACCESS_KEY'] %>
<% aws_secret_key = ENV['AWS_SECRET_KEY'] %>
<% user = "#{`git config --get user.name`.chomp} <#{`git config --get user.email`.chomp}>" %>
---
settings:
  parallel: true

driver:
  name:                 ec2
  require_chef_omnibus: <%= config.chef_version %>
  aws_ssh_key_id:       <%= config.key_id %>
  instance_type:        <%= config.tester_flavor_id %>
  region:               <%= config.region %>
  availability_zone:    <%= config.availability_zone %>
  security_group_ids:   <%= config.security_group_ids %>
  retry_limit:		20
  subnet_id:            <%= config.private_subnet_id %>
<%= config.tags("delphic_snapshots", user, 'Linux', '24h') %>

driver_config:
    name:                ec2
    associate_public_ip: false

provisioner:
  name: chef_zero
  environments_path: 'chef_repo/test/environments'
  attributes:
    chef_client:
      config:
        ssl_verify_mode: ":verify_peer"

transport:
  ssh_key:  <%= ENV['HOME'] %>/.ssh/<%= config.key_id %>.pem
  username: ubuntu

platforms:
  - name: ubuntu 
    driver:
      name:     ec2
      image_id: <%= config.ubuntu_ami %>

suites:
  - name: default
    # use these if you require encrypted data bags:  Setup a submodule:
    # %> git submodule add ssh://git@bitbucket.org:22/delphicdigitaldevops/chef_repo.git
    # then uncoment the below lines:
    data_bags_path: "chef_repo/test/data_bags"
    encrypted_data_bag_secret_key_path: "chef_repo/test/secret"
    # to remove the submodule:
    # %> git submodule deinit -f chef_repo
    # %> git rm chef_repo
    # %> rm -rf .git/modules/chef_repo
    run_list:
      # use this if you are building an application cookbook, and comment out
      # the recipe.  Make sure you add roles/delphic_snapshots.json, and the
      # attribute: default['application'] = 'delphic_snapshots' to
      # attributes/default.rb too.
      # - role[delphic_snapshots]
      - recipe[delphic_snapshots::default]
    attributes:
